# Generated by Django 5.0.2 on 2025-11-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='edad',
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
