# Generated by Django 5.0.2 on 2025-11-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0004_remove_maestros_edad_alter_maestros_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maestros',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
